version: "3.7"

networks:
  web:
    external: true

volumes:
  lpt_website_mysql:

services:
  website:
    image: hub.laravel.pt/website:${TAG:-latest}
    networks: [ web ]
    ports: [ "8000:80" ]
    sysctl:
      kernel.unprivileged_userns_clone: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.website.tls=true"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.service=website"
      - "traefik.http.services.website.loadbalancer.server.port=80"
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'lpt_website_mysql:/var/lib/mysql'
    networks:
      - web
