version: "3.7"

services:
  website:
    restart: always
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage/app/public:/var/www/html/storage/app/public
      - ./storage/logs:/var/www/html/storage/logs
    labels:
      - traefik.http.routers.website.rule=Host(`laravel.pt`)
      - traefik.http.routers.website.tls.certresolver=leresolver
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'lpt_website_mysql:/var/lib/mysql'
    networks:
      - web
