version: "3.7"

services:
  website:
    build:
      context: .
    labels:
      - traefik.http.routers.website.rule=Host(`website.laravel.pt.test`)
      - traefik.http.routers.website.tls=true
    ports: [ "8000:80" ]
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8
    networks: [ web ]
    ports:
      - ${FORWARD_DB_PORT:-33060}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  redis:
    image: redis
    networks: [ web ]
