version: "3.7"

services:
  website:
    restart: always
    volumes:
      - ~/apps/website/.env:/var/www/html/.env
      - ~/apps/website/storage:/var/www/html/storage
    labels:
      - traefik.http.routers.website.rule=Host(`laravel.pt`)
      - traefik.http.routers.website.tls.certresolver=leresolver
