name: Website deployment

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: some experiments
        run: |
          TAG=`date "+%Y%m%d-%H%M%S"`
          echo "website_tag=$TAG" >> $GITHUB_ENV
          docker build -t hub.laravel.pt/website:$TAG .
          docker login -u ${{ secrets.DEPLOY_USER }} -p ${{ secrets.DEPLOY_USER_PASSWORD }} hub.laravel.pt
          docker push hub.laravel.pt/website:$TAG

      - name: Deploy on remote server
        uses: fifsky/ssh-action@master
        with:
          command: |
            echo "${{ env.website_tag }}"
            pwd
            ls -alh
            echo WEBSITE_TAG
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_USER_PRIVATE_KEY }}
